### ISSUE TITLE
undefined symbol: _ZNK2at6Tensor7is_cudaEv

### ISSUE THREAD

**Issue by VintageCar** [Skype-line/X-Avatar#3]
Hi,
Thank you for the great work and codes.
When I follow README.md to run the demo, I got this error as follows:

> Traceback (most recent call last):
>   File "demo.py", line 18, in <module>
>     from lib.xavatar_scan_model import XAVATARSCANModel
>   File "/home/run/code/X-Avatar/code/lib/xavatar_scan_model.py", line 3, in <module>
>     from lib.xavatar_basic_model import XAVATARModel
>   File "/home/run/code/X-Avatar/code/lib/xavatar_basic_model.py", line 17, in <module>
>     from lib.utils.render import render_trimesh, render_joint, weights2colors
>   File "/home/run/code/X-Avatar/code/lib/utils/render.py", line 6, in <module>
>     from pytorch3d.renderer import (
>   File "/home/run/anaconda3/envs/xavatar/lib/python3.7/site-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
>     from .blending import (
>   File "/home/run/anaconda3/envs/xavatar/lib/python3.7/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
>     from pytorch3d import _C
> ImportError: /home/run/anaconda3/envs/xavatar/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv

Have you met such problem before？

By the way ,I think there's a path error on line 26 of setup.py, It should ["code/lib/libmise/mise.pyx"].

Thinks!

**Comment by Skype-line** [comment]
Hi, thanks for your interest in our work.
I didn't encounter such a problem before. "environment.yml" works well on our machine. But it could be because of the [CUDA incompatibility](https://github.com/facebookresearch/pytorch3d/issues/1207#issuecomment-1138208875). We are using cudatoolkit=11.0. Can you try to uncomment the '- cudatoolkit=11.0' in "environment.yml" and create the environment again?
Btw, thank you for pointing out the path error!

**Comment by Skype-line** [comment]
Hope it solves your problem. I will close this issue. :)

**Comment by felixshing** [comment]
I also meet this error and it takes me a whole night to figure out and solve it...

The true reason is that your actual pytorch version is not compatible with pytroch3d, which may be because when you install other packages, they automatically help you upgrade the pytorch version (such as pytorch-lighting)...

In my case, I find the reason is that, when I install environment.yml, I cannot install some packages with pip, leading to all packages that need to be uninstalled via pip cannot be installed. Thus, I choose to manually install the remaining packages via pip. However, when I install them, I did not specfiy the version, leading pytorch-lighting automatically install the newest one and it "by the way" upgrade my pytorch to 1.13, which leads to conflict with previsou installed packages....

So if you want to follow authors's environment.yml, you need to make sure the version of all packages are the same with the environment.yml. Actually, in my another machine, I still install the new packages based on my previous installation and it also works. You just need to make sure the newly added packages will not lead not conflict with the previous ones.
